include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    riverpod_lint: ^3.1.3

linter:
  rules:
    always_specify_types: true
    always_use_package_imports: true
    avoid_void_async: true
    sort_pub_dependencies: true
    unawaited_futures: true
    prefer_const_constructors: true