name: spotimmich
description: "A remote control and image frame for Spotify"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
     - assets/imagePlaceholder.png