// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:key_limepi/lyrics/providers/lyric_classes.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LyricLineAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LyricLineAdapter());
  }
}
